/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.mxab.poetry

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class PoetryPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("poetryInstall") { task ->
            task.doLast {
                println("Installing")
            }
        }
    }
}
