/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.mxab.poetry

import PoetryTask
import org.gradle.api.Plugin
import org.gradle.api.Project

class PoetryPlugin : Plugin<Project> {
    override fun apply(project: Project) {

        val extension = project.extensions.create("poetry", PoetryExtension::class.java)
        project.tasks.register("poetryInstall", PoetryTask::class.java) { task ->
            task.args.add("install")
            task.poetryExec.convention(extension.poetryExec)
        }

//        val stream = ByteArrayOutputStream()
//        project.exec {
//            it.executable = "poetry"
//            it.args("env","info", "--path")
//            it.standardOutput = stream
//        }
//        val envPath = String(stream.toByteArray())
//
//        println(envPath)


    }
}
