/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.mxab.poetry

import org.gradle.api.Project
import org.gradle.api.Plugin

class PoetryPlugin: Plugin<Project> {
    override fun apply(project: Project) {

        project.tasks.register("poetryInstall") { task ->
            task.doLast {
                project.exec {

                    it.executable("poetry")
                    it.args("install")
                }
            }
        }
    }
}
